import os

ALPACA_KEY = os.getenv('ALPACA_API_KEY')
ALPACA_SECRET_KEY = os.getenv('ALPACA_API_SECRET')
ALPACA_PAPER = os.getenv('ALPACA_IS_PAPER')
ALPACA_ENDPOINT = os.getenv('ALPACA_ENDPOINT')

IS_BACKTESTING = bool(os.getenv('IS_BACKTESTING'))

ALPACA_CONFIG = {
     "API_KEY": ALPACA_KEY,
     "API_SECRET": ALPACA_SECRET_KEY,
     "PAPER": ALPACA_PAPER,
 }

POLYGON_KEY = os.getenv('POLYGON_KEY')